// SSMClient: Solid Solutions

const viewSettings = {
	generateIds: true,
	useLongestEdge: true,
	imperialUnits: false,
	imperialRoundToNearest: 1 / 64,
	pages: {
		home: {
			title: 'home',
			layout: [
				{ field: 'name', prefix: 'Name: ', formatter: 'text', grid: { xs: 1, xe: 6, ys: 1, ye: 2 } },
				{ field: 'pdfs.PDF_PROJECT', prefix: 'pdf: ', formatter: 'pdf', grid: { xs: 6, xe: 7, ys: 1, ye: 2 } },
				{ field: 'description', prefix: 'Description: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 2, ye: 3 } },
				{ field: 'configuration', prefix: 'Configuration: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 3, ye: 4 } },
				{ field: 'reportPath', prefix: 'Report Path: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 4, ye: 5 } },
				{ field: 'isDesign', prefix: 'Design: ', formatter: 'boolean', grid: { xs: 1, xe: 3, ys: 5, ye: 6 } },
				{ field: 'isCam', prefix: 'Cam: ', formatter: 'boolean', grid: { xs: 3, xe: 5, ys: 5, ye: 6 } },
				{ field: 'isNesting', prefix: 'Nesting: ', formatter: 'boolean', grid: { xs: 5, xe: 7, ys: 5, ye: 6 } },
				{ field: 'comments', prefix: 'Comments: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 6, ye: 10 } },
				{ field: 'images.IMG_REPORT', formatter: 'eDrawings', grid: { xs: 7, xe: 13, ys: 1, ye: 10 } },
			],
		},
		panels: {
			title: 'Panels',
			groupBy: [
				{ field: 'material.type', title: 'Category' },
				{ field: 'material.name', title: 'Material' },
				{ field: 'material.name', title: 'Material' },
				{ field: 'material.name', title: 'Material' },
				{ field: 'material.name', title: 'Material' },
			],
			table: {
				columns: [
					{ field: 'pdfs.PDF_PANEL', title: '', formatter: 'pdf', width: 50 },
					{ field: 'programs.length', title: '', formatter: 'programIndicator', width: 50 },
					// { field: 'BeamSawIndicator', title: '',    hozAlign: 'center', width: '40' },
					// { field: 'PDFRelativePath', title: '', formatter: 'PDF',  print: false, hozAlign: 'center', width: '40' },
					{ field: 'id', title: '#', hozAlign: 'center', width: 70 },
					// { field: 'id', title: '#',    hozAlign: 'center', width: '50' },
					{ field: 'name', title: 'Part Name' },
					{ field: 'material.name', title: 'Material', width: 300 },
					// { field: 'uid', title: 'Description', formatter: 'qrcode', width: 120 },
					// { field: 'HasEdgebands', title: 'HasEdgebands', formatter: 'tickCross', width:120 },
					// { field: 'images.IMG_PANEL', title: 'image', formatter: 'image', width: 200 },

					{ field: 'length', title: 'Length', width: 120 },
					{ field: 'width', title: 'Width', width: 120 },
					{ field: 'thickness', title: 'Thickness', width: 120 },
					// { field: 'image.relativeUri', title: 'image', width: 120, formatter: 'image' },
					{ field: 'quantity', title: 'Qty', width: 70 },
					{ field: 'hasGrain', title: 'Grain', formatter: 'tickCross', width: 100 },
					{
						field: 'costCore',
						title: 'coreCost',
						width: 120,
						formatter: 'money',
						formatterParams: { decimal: '.', thousand: ',' },
					},
				],
			},
		},
		stocks: {
			title: 'Stocks',
			table: {
				columns: [
					// { field: 'PanelID', title: '#',    hozAlign: 'center', width: '60' },
					{ field: 'name', title: 'Part Name', hozAlign: 'left', width: 'auto' },
					{ field: 'description', title: 'Description', hozAlign: 'center', width: '250' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: '200' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: '200' },
					{ field: 'thickness', title: 'Thickness', hozAlign: 'center', width: '200' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
					{ field: 'material.name', title: 'Material', hozAlign: 'center', width: '250' },
				],
			},
		},
		laminates: {
			title: 'Laminates',
			table: {
				columns: [
					{ field: 'name', title: 'Name' },
					{ field: 'panel.name', title: 'Panel' },
					{ field: 'material.name', title: 'Material' },
					{ field: 'length', title: 'Length' },
					{ field: 'width', title: 'Width' },
					{ field: 'thickness', title: 'Thickness' },
					{ field: 'quantity', title: 'Qty' },
				],
			},
		},
		edgebands: {
			title: 'Edgebands',
			table: {
				columns: [
					{ field: 'panel.name', title: 'Panel', hozAlign: 'left', width: 'auto' },
					{ field: 'material.name', title: 'Material', hozAlign: 'center', width: '250' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: '200' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: '200' },
					{ field: 'thickness', title: 'Thickness', hozAlign: 'center', width: '200' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
				],
			},
		},
		beamSaw: {
			title: 'BeamSaw',
			table: {
				columns: [],
			},
		},
		weldments: {
			title: 'Weldments',
			table: {
				columns: [
					{ field: 'name', title: 'Part Name', hozAlign: 'left', width: 'auto' },
					{ field: 'description', title: 'Description', hozAlign: 'center', width: '250' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: '160' },
					{ field: 'lengthTotal', title: 'Length Total', hozAlign: 'center', width: '160' },
					{ field: 'cutlist', title: 'cutlist', hozAlign: 'center', width: '250' },
					// { field: 'angle1', title: 'Angle 1',    hozAlign: 'center', width: '120' },
					// { field: 'angle2', title: 'Angle 2',    hozAlign: 'center', width: '120' },
					// {field: 'WeldmentBBLength', title: 'BB Length',    hozAlign: 'center', width: '160' },
					// {field: 'WeldmentBBWidth', title: 'BB Width',    hozAlign: 'center', width: '160' },
					// {field: 'WeldmentBBThickness', title: 'BB Thickness',    hozAlign: 'center', width: '160' },
					// {field: 'BBDimensions', title: 'BB Dimensions',    hozAlign: 'center', width: '200' },
					// {field: 'WeldmentBBVolume', title: 'BB Volume',    hozAlign: 'center', width: '160' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
					// {field: 'WeldmentTotalLength', title: 'Total Length',    hozAlign: 'center', width: '160' },
					// { field: 'material.name', title: 'Material',    hozAlign: 'center', width: '150' },
				],
			},
		},
		panelDetails: {
			title: 'Panel Details',
			layout: [
				{ field: 'id', prefix: 'id: ', grid: { xs: 4, xe: 5, ys: 1, ye: 2 } },
				{ field: 'name', prefix: 'Name: ', grid: { xs: 5, xe: 12, ys: 1, ye: 2 } },
				{ field: 'pdfs.PDF_PANEL', prefix: 'pdf: ', formatter: 'pdf', grid: { xs: 12, xe: 13, ys: 1, ye: 2 } },
				{ field: 'description', prefix: 'Description: ', grid: { xs: 4, xe: 8, ys: 2, ye: 3 } },
				{ field: 'configuration', prefix: 'Configuration: ', grid: { xs: 8, xe: 13, ys: 2, ye: 3 } },
				{ field: 'material.key', prefix: 'Material: ', grid: { xs: 4, xe: 8, ys: 4, ye: 5 } },
				{ field: 'length', prefix: 'Length: ', formatter: 'text', grid: { xs: 4, xe: 7, ys: 3, ye: 4 } },
				{ field: 'width', prefix: 'Width: ', formatter: 'text', grid: { xs: 7, xe: 10, ys: 3, ye: 4 } },
				{ field: 'thickness', prefix: 'Thickness: ', formatter: 'text', grid: { xs: 10, xe: 13, ys: 3, ye: 4 } },
				{ field: 'quantity', prefix: 'Quantity: ', formatter: 'text', grid: { xs: 8, xe: 13, ys: 4, ye: 5 } },
				{ field: 'comments', prefix: 'Comments: ', formatter: 'text', grid: { xs: 4, xe: 13, ys: 5, ye: 7 } },
				{ field: 'images.IMG_PANEL', formatter: 'image', grid: { xs: 1, xe: 4, ys: 1, ye: 7 } },
			],
			tables: {
				panels: {
					title: 'Panels',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: '33%' },
							{ field: 'Description', title: 'Description', width: '33%' },
							{ field: 'quantity', title: 'Qty', width: '33%' },
						],
					},
				},
				layers: {
					title: 'Layers',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: '33%' },
							{ field: 'material.name', title: 'Material', width: '33%' },
							{ field: 'thickness', title: 'Thickness', width: '33%' },
						],
					},
				},
				laminates: {
					title: 'Laminates',
					table: {
						columns: [
							{ field: 'name', title: 'Laminate', width: '33%' },
							{ field: 'material.name', title: 'Material', width: '33%' },
							{ field: 'thickness', title: 'Thickness', width: '33%' },
						],
					},
				},
				edgebands: {
					title: 'Edgebands',
					table: {
						columns: [
							{ field: 'name', title: 'Edgebands', width: '33%' },
							{ field: 'material.name', title: 'Material', width: '33%' },
							{ field: 'thickness', title: 'Thickness', width: '33%' },
						],
					},
				},
				panelProcess: {
					title: 'Panel Process',
					table: {
						columns: [
							{ field: 'name', title: 'Process', width: '50%' },
							{ field: 'ZoneName', title: 'Zone', width: '50%' },
						],
					},
				},
				programs: {
					title: 'Programs',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: '50%' },
							{ field: 'machine', title: 'Code', width: '50%' },
						],
					},
				},
			},
		},
		frames: {
			title: 'Frames',
			table: {
				columns: [
					{ field: 'id', title: '#', hozAlign: 'left', width: 70 },
					{ field: 'pdfs.PDF_FRAME', title: '', prefix: 'pdf: ', formatter: 'pdf', width: 50 },
					{ field: 'name', title: 'Name', hozAlign: 'left', width: 'auto' },
					{ field: 'description', title: 'Description', hozAlign: 'center', width: 'auto' },
					{ field: 'height', title: 'Height', hozAlign: 'center', width: '200' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: '200' },
					{ field: 'depth', title: 'Depth', hozAlign: 'center', width: '200' },
					// {field: 'Weight', title: 'Weight',    hozAlign: 'center', width: '200' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '150' },
					// {field: 'Comments', title: 'Comments',    hozAlign: 'center', width: '300' },
					// {field: 'CommentsCP', title: 'Comments',    hozAlign: 'center', width: '300' },
					// {field: 'TotalCost', title: 'Cost', formatter: 'currency',   hozAlign: 'center', width: '150' },
				],
			},
		},
		frameDetails: {
			title: 'Frame Details',
			layout: [
				{ field: 'id', prefix: 'id: ', grid: { xs: 4, xe: 5, ys: 1, ye: 2 } },
				{ field: 'name', prefix: 'Name: ', grid: { xs: 5, xe: 12, ys: 1, ye: 2 } },
				{ field: 'pdfs.PDF_FRAME', prefix: 'pdf: ', formatter: 'pdf', grid: { xs: 12, xe: 13, ys: 1, ye: 2 } },
				{ field: 'description', prefix: 'Description: ', grid: { xs: 4, xe: 9, ys: 2, ye: 3 } },
				{ field: 'configuration', prefix: 'Configuration: ', grid: { xs: 9, xe: 13, ys: 2, ye: 3 } },
				{ field: 'material.key', prefix: 'Material: ', grid: { xs: 4, xe: 9, ys: 3, ye: 4 } },
				{ field: 'quantity', prefix: 'Quantity: ', formatter: 'text', grid: { xs: 9, xe: 13, ys: 3, ye: 4 } },
				{ field: 'comments', prefix: 'Comments: ', formatter: 'text', grid: { xs: 4, xe: 13, ys: 4, ye: 6 } },
				{ field: 'images.IMG_FRAME', formatter: 'image', grid: { xs: 1, xe: 4, ys: 1, ye: 6 } },
			],
			tables: {
				panels: {
					title: 'Panels',
					table: {
						columns: [
							// {field: 'Title', title: 'Panels' },
							{ field: 'id', title: '#', width: '5%' },
							{ field: 'name', title: 'Part Name', width: 'auto' },
							{ field: 'description', title: 'Description', width: '20%' },
							{ field: 'quantity', title: 'Qty', width: '10%' },
							// { field: 'quantityInFrame', title: 'quantityInFrame',  width: '10%' },
							{ field: 'material.name', title: 'Material', width: '15%' },
						],
					},
				},
				hardware: {
					title: 'Hardware',
					table: {
						columns: [
							// {field: 'Title', title: 'Hardware' },
							{ field: 'name', title: 'Name', width: 'auto' },
							{ field: 'description', title: 'Description', width: '25%' },
							{ field: 'configuration', title: 'Configuration', width: '25%' },
							{ field: 'supplier', title: 'Supplier', width: '10%' },
							{ field: 'quantity', title: 'Qty', width: 100 },
							// {field: 'UnitCost', title: 'Unit Cost', formatter: 'currency',  width: '100px' },
							// {field: 'FrameTotalCost', title: 'FrameTotalCost', formatter: 'currency',  width: '100px' },
							// {field: 'TotalCost', title: 'Cost', formatter: 'currency',  width: '100px' },
						],
					},
				},
				programs: {
					title: 'Programs',
					table: {
						columns: [
							// {field: 'Title', title: 'Programs' },
							// {field: 'PartName', title: 'Part Name',  width: '50%' },
							{ field: 'name', title: 'Program', width: '50%' },
							{ field: 'quantity', title: 'Qty', width: '50%' },
						],
					},
				},
				weldments: {
					title: 'Weldments',
					table: {
						columns: [
							{ field: 'name', title: 'Part Name', hozAlign: 'left', width: 'auto' },
							{ field: 'description', title: 'Description', hozAlign: 'center', width: '250' },
							{ field: 'length', title: 'Length', hozAlign: 'center', width: '160' },
							{ field: 'lengthTotal', title: 'Length Total', hozAlign: 'center', width: '160' },
							{ field: 'cutlist', title: 'cutlist', hozAlign: 'center', width: '250' },
							{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
						],
					},
				},
			},
		},
		programs: {
			title: 'Programs',
			showLayers: false,
			showLaminates: false,
			showEdgebands: false,
			showPanelProcess: false,
			table: {
				columns: [
					{ field: 'part.name', title: 'Part Name', hozAlign: 'left', width: 'auto' },
					{ field: 'name', title: 'Program Name', hozAlign: 'center', width: '200' },
					{ field: 'programFile.relativeURI', title: 'Program File Name', hozAlign: 'center', width: '400' },
					// {field: 'length', title: 'Length',    hozAlign: 'center', width: '150' },
					// {field: 'width', title: 'Width',    hozAlign: 'center', width: '150' },
					// {field: 'thickness', title: 'Thickness',    hozAlign: 'center', width: '150' },
					{ field: 'panel.material.name', title: 'Material', hozAlign: 'center', width: '200' },
					// {field: 'Time', title: 'Time',    hozAlign: 'center', width: '200' },
					// {field: 'ProgramCost', title: 'ProgramCost', formatter: 'currency',   hozAlign: 'center', width: '200' },
					{ field: 'machine', title: 'Machine', hozAlign: 'center', width: '150' },
					{
						field: 'cost',
						title: 'Cost',
						width: '150',
						formatter: 'money',
						formatterParams: { decimal: '.', thousand: ',' },
					},
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '75' },
				],
			},
		},
		programDetails: {
			title: 'Program Details',
			layout: [
				{ field: 'name', prefix: 'Name: ', grid: { xs: 4, xe: 12, ys: 1, ye: 2 } },
				{ field: 'programFile.relativeURI', formatter: 'link', grid: { xs: 12, xe: 13, ys: 1, ye: 2 } },
				// { field: 'programFilepath', formatter: 'link', grid: { xs: 12, xe: 13, ys: 1, ye: 2 } },
				{ field: 'description', prefix: 'Description: ', grid: { xs: 4, xe: 9, ys: 2, ye: 3 } },
				{ field: 'configuration', prefix: 'Configuration: ', grid: { xs: 9, xe: 13, ys: 2, ye: 3 } },
				{ field: 'material.name', prefix: 'Material: ', grid: { xs: 4, xe: 9, ys: 4, ye: 5 } },
				{ field: 'length', prefix: 'Length: ', formatter: 'text', grid: { xs: 4, xe: 7, ys: 3, ye: 4 } },
				{ field: 'width', prefix: 'Width: ', formatter: 'text', grid: { xs: 7, xe: 10, ys: 3, ye: 4 } },
				{ field: 'thickness', prefix: 'Thickness: ', formatter: 'text', grid: { xs: 10, xe: 13, ys: 3, ye: 4 } },
				{ field: 'quantity', prefix: 'Quantity: ', formatter: 'text', grid: { xs: 9, xe: 13, ys: 4, ye: 5 } },
				{ field: 'comments', prefix: 'Comments: ', formatter: 'text', grid: { xs: 4, xe: 13, ys: 5, ye: 7 } },
				{ field: 'images.IMG_PROGRAM', formatter: 'image', grid: { xs: 1, xe: 4, ys: 1, ye: 7 } },
			],
			tables: {
				tools: {
					title: 'Tools',
					table: {
						columns: [
							{ field: 'name', title: 'Name' },
							{ field: 'number', title: 'number' },
							{ field: 'diameter', title: 'diameter' },
						],
					},
				},
			},
		},
		sheets: {
			title: 'Sheets',
			table: {
				columns: [
					{ field: 'name', title: 'Name', hozAlign: 'left', width: '600' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: 'auto' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: 'auto' },
					{ field: 'thickness', title: 'Thickness', hozAlign: 'center', width: 'auto' },
					{ field: 'material.name', title: 'Material', hozAlign: 'center', width: 'auto' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: 'auto' },
				],
			},
		},
		sheetDetails: {
			title: 'Sheet Details',
			showTools: true,
			layout: [
				{ field: 'name', prefix: 'Name: ', grid: { xs: 1, xe: 13, ys: 1, ye: 2 } },
				{ field: 'length', prefix: 'Length: ', grid: { xs: 1, xe: 7, ys: 2, ye: 3 } },
				{ field: 'width', prefix: 'Width: ', grid: { xs: 1, xe: 7, ys: 3, ye: 4 } },
				{ field: 'thickness', prefix: 'Thickness: ', grid: { xs: 1, xe: 7, ys: 4, ye: 5 } },
				{ field: 'quantity', prefix: 'Quantity: ', formatter: 'text', grid: { xs: 7, xe: 13, ys: 2, ye: 3 } },
				{ field: 'material.name', prefix: 'Material: ', formatter: 'text', grid: { xs: 7, xe: 13, ys: 3, ye: 4 } },
				{ field: 'comments', prefix: 'Comments: ', formatter: 'text', grid: { xs: 1, xe: 13, ys: 5, ye: 7 } },
			],
			tables: {
				panels: {
					title: 'Panels',
					table: {
						columns: [
							{ field: 'nestingId', title: 'Nesting ID', hozAlign: 'center', width: '10%' },
							{ field: 'name', title: 'Name', hozAlign: 'center', width: 'auto' },
							{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: 'auto' },
						],
					},
				},
				tools: {
					title: 'Tools',
					table: {
						columns: [
							{ field: 'name', title: 'Name' },
							{ field: 'number', title: 'number' },
							{ field: 'diameter', title: 'diameter' },
						],
					},
				},
			},
		},
		programParts: {
			title: 'Nested Panels',
			table: {
				columns: [
					{ field: 'ProgramIndicator', title: '', hozAlign: 'center', width: '40' },
					{ field: 'PanelID', title: '#', hozAlign: 'center', width: '60' },
					{ field: 'name', title: 'Name', hozAlign: 'left', width: '600' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: 'auto' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: 'auto' },
					{ field: 'thickness', title: 'Thickness', hozAlign: 'center', width: 'auto' },
					{ field: 'material.name', title: 'Material', hozAlign: 'center', width: 'auto' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: 'auto' },
				],
			},
		},
		cuttingPattern: {
			title: 'Cutting Patterns',
			table: {
				columns: [
					{ field: 'name', title: 'Name', hozAlign: 'left', width: 'auto' },
					// {field: 'usedAreaPercentage', title: 'usedAreaPercentage',    hozAlign: 'center', width: '200' },
					// {field: 'wasteAreaPercentage', title: 'wasteAreaPercentage',    hozAlign: 'center', width: '200' },
					// {field: 'trimAreaPercentage', title: 'trimAreaPercentage',    hozAlign: 'center', width: '200' },
					// {field: 'paddingAreaPercentage', title: 'paddingAreaPercentage',    hozAlign: 'center', width: '200' },
					// {field: 'usedAreaFormatted', title: 'usedAreaFormatted',    hozAlign: 'center', width: '200' },

					{ field: 'panelCount', title: 'panelCount', hozAlign: 'center', width: '200' },
					{ field: 'length', title: 'Length', hozAlign: 'center', width: '200' },
					{ field: 'width', title: 'Width', hozAlign: 'center', width: '200' },
					{ field: 'material', title: 'Material', hozAlign: 'center', width: '200' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
				],
			},
		},
		cuttingPatternDetails: {
			title: 'Cutting Pattern Details',
			panelIdField: 'id',
			showStatistics: true,
			printStatistics: true,
			showCutList: true,
			printCutList: true,
			showPanelIds: true,
			showPanelDimensions: true,
			showWasteIds: false,
			showWasteDimensions: false,
			showTrimIds: false,
			showTrimDimensions: false,
			layout: [
				{ field: 'name', prefix: 'Name: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 1, ye: 2 } },
				{ field: 'material', prefix: 'Material: ', formatter: 'text', grid: { xs: 7, xe: 13, ys: 1, ye: 2 } },
				{ field: 'length', prefix: 'Length: ', formatter: 'text', grid: { xs: 1, xe: 7, ys: 2, ye: 3 } },
				{ field: 'width', prefix: 'Width: ', formatter: 'text', grid: { xs: 7, xe: 13, ys: 2, ye: 3 } },
			],
			tables: {
				panels: {
					title: 'Panels',
					table: {
						columns: [
							{ field: 'id', title: 'id', hozAlign: 'center', width: '10%' },
							{ field: 'name', title: 'Name', hozAlign: 'center', width: 'auto' },
						],
					},
				},
			},
		},
		hardware: {
			title: 'Hardware',
			table: {
				columns: [
					{ field: 'images.IMG_HARDWARE', title: 'image', formatter: 'image', hozAlign: 'center', width: 150 },
					{ field: 'name', title: 'Name', hozAlign: 'left', width: 'auto' },
					{ field: 'description', title: 'Description', hozAlign: 'center', width: 'auto' },
					{ field: 'configuration', title: 'Configuration', hozAlign: 'center', width: '300' },
					{ field: 'reference', title: 'Reference', hozAlign: 'center', width: 'auto' },
					{ field: 'supplier', title: 'Supplier', hozAlign: 'center', width: 'auto' },
					{ field: 'quantity', title: 'Qty', hozAlign: 'center', width: '100' },
					{
						field: 'costUnit',
						title: 'Unit Cost',
						width: '200',
						formatter: 'money',
						formatterParams: { decimal: '.', thousand: ',' },
					},
				],
			},
		},
		summary: {
			title: 'Summary',
			showMachiningCosts: false,
			showSummaryChart: true,
			showSummaryCuttingPatternTable: true,
			PrintSummaryChart: true,
			tables: {
				materials: {
					title: 'Materials',
					table: {
						columns: [
							{ field: 'name', title: 'Material', width: 'auto' },
							{ field: 'description', title: 'Description', width: '20%' },
							{ field: 'thickness', title: 'Thickness', width: '12%' },
							{ field: 'quantity', title: 'Quantity', width: '12%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				laminates: {
					title: 'Laminates',
					table: {
						columns: [
							{ field: 'name', title: 'Material', width: 'auto' },
							{ field: 'description', title: 'Description', width: '20%' },
							{ field: 'thickness', title: 'Thickness', width: '12%' },
							{ field: 'quantity', title: 'Quantity', width: '12%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				edgebands: {
					title: 'Edgebands',
					table: {
						columns: [
							{ field: 'name', title: 'Material', width: 'auto' },
							{ field: 'description', title: 'Description', width: '20%' },
							{ field: 'thickness', title: 'Thickness', width: '12%' },
							{ field: 'quantity', title: 'Quantity', width: '12%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				weldments: {
					title: 'Weldments',
					table: {
						columns: [
							{ field: 'name', title: 'Material', width: 'auto' },
							{ field: 'description', title: 'Description', width: '32%' },
							// {field: 'MaterialThickness', title: 'Thickness',  width: '12%' },
							{ field: 'quantity', title: 'Quantity', width: '12%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				paint: {
					title: 'Paint',
					table: {
						columns: [
							{ field: 'material.name', title: 'Paint', width: 'auto' },
							{ field: 'MaterialDescription', title: 'Description', width: '32%' },
							// {field: 'MaterialThickness', title: 'Thickness',  width: '12%' },
							{ field: 'MaterialQuantity', title: 'Quantity', width: '12%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'MaterialUnitCost',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'TotalCost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				hardware: {
					title: 'Hardware',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: 'auto' },
							{ field: 'configuration', title: 'Configuration', width: '20%' },
							// {field: 'Supplier', title: 'Supplier', width: 'auto' },
							{ field: 'reference', title: 'Reference', width: '12%' },
							{ field: 'quantity', title: 'Quantity', width: '12%' },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '14%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				panelProcesses: {
					title: 'Panel Process',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: '25%' },
							{ field: 'quantity', title: 'Quantity', width: '25%', formatter: 'number', formatterParams: { precision: 2 } },
							{
								field: 'costUnit',
								title: 'Unit Cost',
								width: '25%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '25%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				labour: {
					title: 'Labour Costs',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: 'auto' },
							{
								field: 'LabourCosts',
								title: 'Cost',
								width: '12%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
				machining: {
					title: 'Machining Costs',
					table: {
						columns: [
							{ field: 'name', title: 'Name', width: '20%' },
							{ field: 'time', title: 'Time', width: '20%' },
							{ field: 'quantity', title: 'Quantity', width: '20%' },
							{
								field: 'costHour',
								title: 'Hourly Cost',
								width: '20%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
							{
								field: 'cost',
								title: 'Cost',
								width: '20%',
								formatter: 'money',
								formatterParams: { decimal: '.', thousand: ',', symbol: '£' },
								bottomCalc: 'sum',
								bottomCalcFormatter: 'money',
								bottomCalcFormatterParams: { decimal: '.', thousand: ',', symbol: '£' },
							},
						],
					},
				},
			},
		},
	},
	labels: {
		panels: {
			excludePanelLabels: false,
			excludeOffcutLabels: true,
			layout: [
				{ field: 'programs.length', formatter: 'programIndicator', grid: { xs: 1, xe: 2, ys: 1, ye: 2 } },
				{ field: 'id', grid: { xs: 2, xe: 4, ys: 1, ye: 2 } },
				{ field: 'name', wrapText: true, grid: { xs: 4, xe: 13, ys: 1, ye: 2 } },
				{ field: 'images.IMG_PANEL', formatter: 'image', grid: { xs: 7, xe: 13, ys: 2, ye: 6 } },
				{ field: 'material.name', grid: { xs: 1, xe: 7, ys: 2, ye: 3 } },
				{ field: 'description', grid: { xs: 1, xe: 7, ys: 3, ye: 4 } },
				{ field: 'instance', grid: { xs: 1, xe: 7, ys: 4, ye: 5 } },
				{ field: 'Instance', formatter: 'qrcode', grid: { xs: 1, xe: 7, ys: 5, ye: 6 } },
			],
			settings: {
				columns: 2,
				rows: 5,
				pageHeight: 297,
				pageWidth: 210,
				pagePaddingTop: 5,
				pagePaddingBottom: 5,
				pagePaddingLeft: 5,
				pagePaddingRight: 5,
				pageGapVertical: 5,
				pageGapHorizontal: 5,
				labelPadding: 2,
				fontSize: 15,
			},
		},
		programParts: {
			excludeNestedPanelLabels: false,
			excludeOffcutLabels: true,
			layout: [],
			settings: {
				columns: 2,
				rows: 5,
				pageHeight: 297,
				pageWidth: 210,
				pagePaddingTop: 5,
				pagePaddingBottom: 5,
				pagePaddingLeft: 5,
				pagePaddingRight: 5,
				pageGapVertical: 5,
				pageGapHorizontal: 5,
				labelPadding: 2,
				fontSize: 15,
			},
		},
		beamSaw: {
			layout: [],
			settings: {
				columns: 2,
				rows: 5,
				pageHeight: 297,
				pageWidth: 210,
				pagePaddingTop: 5,
				pagePaddingBottom: 5,
				pagePaddingLeft: 5,
				pagePaddingRight: 5,
				pageGapVertical: 5,
				pageGapHorizontal: 5,
				labelPadding: 2,
				fontSize: 15,
			},
		},
		frames: {
			layout: [
				{ field: 'name', grid: { xs: 3, xe: 13, ys: 1, ye: 2 } },
				{ field: 'images.IMG_FRAME', formatter: 'image', grid: { xs: 7, xe: 13, ys: 2, ye: 5 } },
				{ field: 'description', grid: { xs: 1, xe: 7, ys: 2, ye: 3 } },
				{ field: 'assets/company-logo-label.png', formatter: 'image', grid: { xs: 1, xe: 3, ys: 1, ye: 2 } },
				{ field: '«height» x «width» x «depth»', grid: { xs: 1, xe: 7, ys: 3, ye: 4 } },
				// { field: '«height»x«width»', grid: { xs: 1, xe: 7, ys: 3, ye: 4 } },
				{ field: 'instance', grid: { xs: 1, xe: 7, ys: 4, ye: 5 } },
			],
			settings: {
				columns: 2,
				rows: 5,
				pageHeight: 297,
				pageWidth: 210,
				pagePaddingTop: 5,
				pagePaddingBottom: 5,
				pagePaddingLeft: 5,
				pagePaddingRight: 5,
				pageGapVertical: 5,
				pageGapHorizontal: 5,
				labelPadding: 2,
				fontSize: 15,
			},
		},
	},
	print: {
		header: {
			showHeader: true,
			showCompanyLogo: true,
			columns: [
				{ field: 'ProjectName', prefix: 'Project' },
				{ field: 'CreatedBy', prefix: 'Created By' },
				{ field: 'ProjectPath', prefix: 'Project Path' },
				{ field: 'ProjectQuantity', prefix: 'Project Quantity' },
				{ field: 'Customer', prefix: 'Customer' },
				{ field: 'OrderNumber', prefix: 'Order Number' },
				{ field: 'Date', prefix: 'Date' },
				{ field: 'PDFRelativePath', prefix: 'PDF' },
				{ field: 'ProjectComments', prefix: 'Comments' },
			],
		},
		pages: [
			{ page: 'Home' },
			{ page: 'Frames' },
			// { page: 'Frame Details' },
			{ page: 'Panels' },
			// { page: 'Panel Details' },
			// { page: 'Panel Detailed List' },
			{ page: 'Weldments' },
			{ page: 'Stocks' },
			{ page: 'Beam Saw' },
			{ page: 'Edgebands' },
			{ page: 'Laminates' },
			{ page: 'Programs' },
			// { page: 'Program Detailed List' },
			// { page: 'Program Details' },
			{ page: 'Sheets' },
			// { page: 'Sheet Details' },
			// { page: 'Sheet Detailed List' },
			{ page: 'Cutting Pattern' },
			{ page: 'Nested Panels' },
			{ page: 'Tool List' },
			{ page: 'Hardware' },
			{ page: 'Summary' },
		],
	},
}

try {
	module.exports = { viewSettings }
} catch {}
